export const GlobalStyles={
    colors:{
            primary50: '#008921',
            primary100: '#c6affc',
            primary200: '#a281f0',
            primary400: '#3b7a57 ',
            primary500: '#B3E5BE',//#3e04c3
            primary700: 'white',
            primaryButtonColor: 'white',
            accent500: 'black',
            error50: '#FF0000',
            error500: '#9b095c',
            gray500: '#39324a',
            gray700: '#221c30',
            backroundColor:'white',
            manageProductionInformationBackground:'white',
            headerColor:'#edf6f9',
            text_border_button:"#008921",
            button1:"#008921",
            buttonTextColor:"black",
            inputBox:"White",
            deleteButton:"#760000",
            titleBackground:'white',
            titleText:"black",
            textcolor:"black",
            inputtextcolor:"gray",
            defectsBackground:'white',
            inputBackgroundColor:'#FFFF',
    }
}